import Foundation

/// Installs `age-plugin-passeport` and derives the age recipient, completing
/// the GnuPG-free encryption path. The plugin wraps to the cv25519 encryption
/// subkey; decryption routes back through the app bridge (Touch ID-gated), so
/// the seed never leaves Passeport.
enum AgeConfigurator {
    struct Result {
        let pluginPath: String
        let binDirectory: String
        let recipient: String
        let identity: String
        let identityFilePath: String
    }

    enum AgeError: LocalizedError {
        case noEncryptionKey
        case helperFailed(String)

        var errorDescription: String? {
            switch self {
            case .noEncryptionKey:
                "Derive your keys first so the encryption key is available."
            case .helperFailed(let message):
                "Could not compute the age recipient: \(message)"
            }
        }
    }

    /// Write the plugin wrapper and return the recipient/identity strings.
    /// `encryptionPublicKeyHex` is the 32-byte X25519 point; `helperPath` is
    /// the bundled `passeport-core`; `socketPath` is the bridge socket the
    /// plugin uses for decryption.
    static func configure(
        encryptionPublicKeyHex: String,
        helperPath: String,
        socketPath: String
    ) throws -> Result {
        let (recipient, identity) = try ageRecipient(
            helperPath: helperPath,
            encryptionPublicKeyHex: encryptionPublicKeyHex
        )

        let dir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Passeport", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let plugin = dir.appendingPathComponent("age-plugin-passeport")

        // age discovers the plugin by name on PATH and invokes it with
        // `--age-plugin=<state>`; the wrapper injects the socket and forwards.
        let script = """
        #!/bin/bash
        # Generated by Passeport. age-plugin-passeport bridges age to the
        # running Passeport app for Touch ID-gated decryption.
        export PASSEPORT_SCD_SOCKET=\(ShellQuote.quote(socketPath))
        exec \(ShellQuote.quote(helperPath)) "$@"
        """
        try script.write(to: plugin, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: plugin.path)
        let pluginLink = try installPluginLink(at: plugin)

        let identityFile = try writeIdentityFile(in: dir, recipient: recipient, identity: identity)

        return Result(
            pluginPath: plugin.path,
            binDirectory: pluginLink.deletingLastPathComponent().path,
            recipient: recipient,
            identity: identity,
            identityFilePath: identityFile.path
        )
    }

    private static func installPluginLink(at plugin: URL) throws -> URL {
        let localBin = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".local/bin", isDirectory: true)
        try FileManager.default.createDirectory(at: localBin, withIntermediateDirectories: true)
        let linkedPlugin = localBin.appendingPathComponent(plugin.lastPathComponent)

        if FileManager.default.fileExists(atPath: linkedPlugin.path) {
            try FileManager.default.removeItem(at: linkedPlugin)
        }

        try FileManager.default.createSymbolicLink(
            at: linkedPlugin,
            withDestinationURL: plugin
        )

        return linkedPlugin
    }

    /// Write the identity file `age -d -i` points at. The identity string is
    /// only a handle (decryption still goes through the app, Touch ID-gated),
    /// but keep it 0600 like any age identity file. Overwrites on re-run.
    private static func writeIdentityFile(in dir: URL, recipient: String, identity: String) throws -> URL {
        let ageDir = dir.appendingPathComponent("age", isDirectory: true)
        try FileManager.default.createDirectory(at: ageDir, withIntermediateDirectories: true)
        let file = ageDir.appendingPathComponent("identity.txt")
        let contents = """
        # created by Passeport — decrypts via the running app (Touch ID-gated)
        # recipient: \(recipient)
        \(identity)

        """
        try contents.write(to: file, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: file.path)
        return file
    }

    private static func ageRecipient(
        helperPath: String,
        encryptionPublicKeyHex: String
    ) throws -> (recipient: String, identity: String) {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: helperPath)
        process.arguments = ["age-recipient"]
        let stdin = Pipe(), stdout = Pipe(), stderr = Pipe()
        process.standardInput = stdin
        process.standardOutput = stdout
        process.standardError = stderr
        try process.run()
        stdin.fileHandleForWriting.write(Data(encryptionPublicKeyHex.utf8))
        try stdin.fileHandleForWriting.close()

        let output = stdout.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        guard process.terminationStatus == 0,
              let object = try? JSONSerialization.jsonObject(with: output) as? [String: Any],
              let recipient = object["recipient"] as? String,
              let identity = object["identity"] as? String else {
            let message = String(data: stderr.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)?
                .trimmingCharacters(in: .whitespacesAndNewlines) ?? "unknown error"
            throw AgeError.helperFailed(message)
        }
        return (recipient, identity)
    }
}
