import Foundation

/// Installs Passeport's native `age` command, keeps `age-plugin-passeport` for
/// optional external age/rage interoperability, and derives the standard
/// X25519 recipient. Decryption routes through the app's approval policy.
enum AgeConfigurator {
    struct Result {
        let programPath: String
        let pluginPath: String
        let binDirectory: String
        let recipient: String
        let identity: String
        let identityFilePath: String
    }

    enum AgeError: LocalizedError {
        case helperFailed(String)

        var errorDescription: String? {
            switch self {
            case .helperFailed(let message):
                "Could not compute the age recipient: \(message)"
            }
        }
    }

    /// Write the native CLI + optional plugin wrappers and return the public
    /// recipient/plugin identity strings.
    /// `recipient` is the canonical age1 value already displayed by the app;
    /// `helperPath` is the bundled `passeport-core`; `socketPath` is the bridge
    /// socket the plugin uses for decryption.
    static func configure(
        recipient: String,
        helperPath: String,
        socketPath: String,
        installStandardAlias: Bool = false
    ) throws -> Result {
        let (canonicalRecipient, identity) = try ageIdentity(
            helperPath: helperPath,
            recipient: recipient
        )

        let dir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Passeport", isDirectory: true)
            .appendingPathComponent("age", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        // The main command encrypts with the upstream age library and sends
        // complete ciphertext to the app for gated decryption.
        let legacyProgram = dir.appendingPathComponent("age")
        let program = dir.appendingPathComponent("passeport-age")
        let programScript = """
        #!/bin/bash
        # Generated by Passeport. Encryption is public; decryption is Touch
        # approval-controlled through the running Passeport app.
        export PASSEPORT_SCD_SOCKET=\(ShellQuote.quote(socketPath))
        exec \(ShellQuote.quote(helperPath)) age "$@"
        """
        try programScript.write(to: program, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: program.path)

        let plugin = dir.appendingPathComponent("age-plugin-passeport")

        // age discovers the plugin by name on PATH and invokes it with
        // `--age-plugin=<state>`; the wrapper injects the socket and forwards.
        let script = """
        #!/bin/bash
        # Generated by Passeport. age-plugin-passeport bridges age to the
        # running Passeport app for approval-controlled decryption.
        export PASSEPORT_SCD_SOCKET=\(ShellQuote.quote(socketPath))
        exec \(ShellQuote.quote(helperPath)) "$@"
        """
        try script.write(to: plugin, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: plugin.path)
        let programLink = try installLink(at: program)
        try updateStandardAlias(
            named: "age",
            target: program,
            legacyTarget: legacyProgram,
            enabled: installStandardAlias
        )
        _ = try installLink(at: plugin)

        let identityFile = try writeIdentityFile(in: dir, recipient: canonicalRecipient, identity: identity)

        return Result(
            programPath: program.path,
            pluginPath: plugin.path,
            binDirectory: programLink.deletingLastPathComponent().path,
            recipient: canonicalRecipient,
            identity: identity,
            identityFilePath: identityFile.path
        )
    }

    private static func installLink(at program: URL) throws -> URL {
        let localBin = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".local/bin", isDirectory: true)
        try FileManager.default.createDirectory(at: localBin, withIntermediateDirectories: true)
        let linkedProgram = localBin.appendingPathComponent(program.lastPathComponent)

        if FileManager.default.fileExists(atPath: linkedProgram.path) {
            try FileManager.default.removeItem(at: linkedProgram)
        }

        try FileManager.default.createSymbolicLink(
            at: linkedProgram,
            withDestinationURL: program
        )

        return linkedProgram
    }

    private static func updateStandardAlias(
        named name: String,
        target: URL,
        legacyTarget: URL,
        enabled: Bool
    ) throws {
        let alias = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".local/bin", isDirectory: true)
            .appendingPathComponent(name)
        let ownedTargets = [target.path, legacyTarget.path]
        let existingTarget = try? FileManager.default.destinationOfSymbolicLink(atPath: alias.path)
        let isOwned = existingTarget.map { ownedTargets.contains(URL(fileURLWithPath: $0, relativeTo: alias.deletingLastPathComponent()).standardized.path) } ?? false

        guard enabled else {
            if isOwned { try FileManager.default.removeItem(at: alias) }
            return
        }
        if FileManager.default.fileExists(atPath: alias.path) || existingTarget != nil {
            guard isOwned else {
                throw CocoaError(.fileWriteFileExists, userInfo: [
                    NSFilePathErrorKey: alias.path,
                    NSLocalizedDescriptionKey: "Cannot install the `age` alias because \(alias.path) is not managed by Passeport."
                ])
            }
            try FileManager.default.removeItem(at: alias)
        }
        try FileManager.default.createSymbolicLink(at: alias, withDestinationURL: target)
    }

    /// Write the identity file `age -d -i` points at. The identity string is
    /// only a handle (decryption still goes through the app's approval policy),
    /// but keep it 0600 like any age identity file. Overwrites on re-run.
    private static func writeIdentityFile(in dir: URL, recipient: String, identity: String) throws -> URL {
        let file = dir.appendingPathComponent("identity.txt")
        let contents = """
        # created by Passeport — decrypts via the running app (approval-controlled)
        # recipient: \(recipient)
        \(identity)

        """
        try contents.write(to: file, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: file.path)
        return file
    }

    private static func ageIdentity(
        helperPath: String,
        recipient: String
    ) throws -> (recipient: String, identity: String) {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: helperPath)
        process.arguments = ["age-recipient"]
        let stdin = Pipe(), stdout = Pipe(), stderr = Pipe()
        process.standardInput = stdin
        process.standardOutput = stdout
        process.standardError = stderr
        try process.run()
        stdin.fileHandleForWriting.write(Data(recipient.utf8))
        try stdin.fileHandleForWriting.close()

        let output = stdout.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        guard process.terminationStatus == 0,
              let object = try? JSONSerialization.jsonObject(with: output) as? [String: Any],
              let recipient = object["recipient"] as? String,
              let identity = object["identity"] as? String else {
            let message = String(data: stderr.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)?
                .trimmingCharacters(in: .whitespacesAndNewlines) ?? "unknown error"
            throw AgeError.helperFailed(message)
        }
        return (recipient, identity)
    }
}
