import Foundation

/// Configures the GNU-free OpenPGP path: a self-contained
/// `passeport-gpg` wrapper that runs the bundled pure-Rust gpg drop-in, signing
/// through the app bridge under the app's approval policy. This uses no GnuPG
/// binary at all. It lives in its own
/// directory with its own public-key file, so it never shadows the system gpg
/// or the user's `~/.gnupg`.
enum GnuFreeGPGConfigurator {
    static var health: IntegrationHealth {
        managedCommandHealth(command: "passeport-gpg", directory: "openpgp-mode2")
    }

    static func remove() throws {
        try removeManagedCommandLinks(names: ["passeport-gpg", "gpg"], directory: "openpgp-mode2")
    }
    struct Result {
        /// The wrapper to point `git config gpg.program` at.
        let gpgProgramPath: String
        let gnupgHome: String
        let publicKeyPath: String
    }

    /// Write the managed home (public key + wrapper). `publicKeyArmored` is the
    /// OpenPGP public key; `helperPath` is the bundled `passeport-core`;
    /// `socketPath` is the bridge socket the wrapper signs through.
    static func configure(
        publicKeyArmored: String,
        helperPath: String,
        socketPath: String,
        installStandardAlias: Bool = false
    ) throws -> Result {
        let home = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Passeport", isDirectory: true)
            .appendingPathComponent("openpgp-mode2", isDirectory: true)
        try FileManager.default.createDirectory(at: home, withIntermediateDirectories: true)
        try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: home.path)

        // The drop-in reads its one public key from $GNUPGHOME/passeport-pubkey.asc.
        let pubKey = home.appendingPathComponent("passeport-pubkey.asc")
        var armored = publicKeyArmored
        if !armored.hasSuffix("\n") { armored += "\n" }
        try armored.write(to: pubKey, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: pubKey.path)

        // git's gpg.program points at this wrapper; it injects the bridge socket
        // and the managed GNUPGHOME, then runs the bundled gpg command. Invoking
        // the helper as `<helper> gpg …` routes it to the gpg CLI dialect.
        let wrapper = home.appendingPathComponent("passeport-gpg")
        let script = """
        #!/bin/bash
        # Generated by Passeport. GNU-free OpenPGP: runs the bundled
        # pure-Rust gpg drop-in, signing through the app (approval-controlled).
        export PASSEPORT_SCD_SOCKET=\(ShellQuote.quote(socketPath))
        export GNUPGHOME=\(ShellQuote.quote(home.path))
        exec \(ShellQuote.quote(helperPath)) gpg "$@"
        """
        try script.write(to: wrapper, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: wrapper.path)

        // Also expose it on PATH for manual use; git uses the absolute path above.
        try installLink(wrapper: wrapper)
        try updateStandardAlias(target: wrapper, enabled: installStandardAlias)

        return Result(
            gpgProgramPath: wrapper.path,
            gnupgHome: home.path,
            publicKeyPath: pubKey.path
        )
    }

    private static func installLink(wrapper: URL) throws {
        let localBin = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".local/bin", isDirectory: true)
        try FileManager.default.createDirectory(at: localBin, withIntermediateDirectories: true)
        let link = localBin.appendingPathComponent(wrapper.lastPathComponent)
        if FileManager.default.fileExists(atPath: link.path) {
            try FileManager.default.removeItem(at: link)
        }
        try FileManager.default.createSymbolicLink(at: link, withDestinationURL: wrapper)
    }

    private static func updateStandardAlias(target: URL, enabled: Bool) throws {
        let alias = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".local/bin", isDirectory: true)
            .appendingPathComponent("gpg")
        let existingTarget = try? FileManager.default.destinationOfSymbolicLink(atPath: alias.path)
        let resolvedTarget = existingTarget.map {
            URL(fileURLWithPath: $0, relativeTo: alias.deletingLastPathComponent()).standardized.path
        }
        let isOwned = resolvedTarget == target.standardized.path

        guard enabled else {
            if isOwned { try FileManager.default.removeItem(at: alias) }
            return
        }
        if FileManager.default.fileExists(atPath: alias.path) || existingTarget != nil {
            guard isOwned else {
                throw CocoaError(.fileWriteFileExists, userInfo: [
                    NSFilePathErrorKey: alias.path,
                    NSLocalizedDescriptionKey: "Cannot install the `gpg` alias because \(alias.path) is not managed by Passeport."
                ])
            }
            try FileManager.default.removeItem(at: alias)
        }
        try FileManager.default.createSymbolicLink(at: alias, withDestinationURL: target)
    }
}
