import Foundation

/// Installs a single `minisign` command and writes the public-key file. It runs
/// Passeport's own minisign CLI: signing uses the seed-derived key and routes
/// through the app bridge (Touch ID-gated, so the seed never leaves Passeport);
/// verification is fully public and works on any minisign/rsign signature.
enum MinisignConfigurator {
    struct Result {
        let publicKeyPath: String
        let programPath: String
        let binDirectory: String
    }

    /// Write `passeport.pub` and a `minisign` wrapper, then symlink it into
    /// `~/.local/bin`. `publicKeyFile` is the minisign public-key file contents;
    /// `helperPath` is the bundled `passeport-core`; `socketPath` is the bridge
    /// socket the wrapper signs through.
    static func configure(
        publicKeyFile: String,
        helperPath: String,
        socketPath: String
    ) throws -> Result {
        let dir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Passeport", isDirectory: true)
            .appendingPathComponent("minisign", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        let publicKey = dir.appendingPathComponent("passeport.pub")
        var contents = publicKeyFile
        if !contents.hasSuffix("\n") { contents += "\n" }
        try contents.write(to: publicKey, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o644], ofItemAtPath: publicKey.path)

        // A single `minisign`: `-S` signs through the app, `-V` verifies, `-R`
        // prints your public key. The wrapper injects the bridge socket (for
        // signing) and the public-key path (for -R / default verify).
        let program = dir.appendingPathComponent("minisign")
        let script = """
        #!/bin/bash
        # Generated by Passeport. One command: `minisign -Sm <file>` signs (Touch
        # ID-gated through the app); `minisign -Vm <file> -p <key>` verifies.
        export PASSEPORT_SCD_SOCKET=\(ShellQuote.quote(socketPath))
        export PASSEPORT_MINISIGN_PUBKEY=\(ShellQuote.quote(publicKey.path))
        exec \(ShellQuote.quote(helperPath)) minisign "$@"
        """
        try script.write(to: program, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: program.path)

        let binDir = try installLink(program: program)

        return Result(
            publicKeyPath: publicKey.path,
            programPath: program.path,
            binDirectory: binDir.path
        )
    }

    private static func installLink(program: URL) throws -> URL {
        let localBin = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".local/bin", isDirectory: true)
        try FileManager.default.createDirectory(at: localBin, withIntermediateDirectories: true)
        let link = localBin.appendingPathComponent(program.lastPathComponent)
        if FileManager.default.fileExists(atPath: link.path) {
            try FileManager.default.removeItem(at: link)
        }
        try FileManager.default.createSymbolicLink(at: link, withDestinationURL: program)
        return localBin
    }
}
