import Foundation

/// Installs a single `minisign` command and writes the public-key file. It runs
/// Passeport's own minisign CLI: signing uses the seed-derived key and routes
/// through the app bridge (approval-controlled, so the seed never leaves Passeport);
/// verification is fully public and works on any minisign/rsign signature.
enum MinisignConfigurator {
    static var health: IntegrationHealth {
        managedCommandHealth(command: "passeport-minisign", directory: "minisign")
    }

    static func remove() throws {
        try removeManagedCommandLinks(names: ["passeport-minisign", "minisign"], directory: "minisign")
        let publicKey = FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".minisign/passeport.pub")
        try? FileManager.default.removeItem(at: publicKey)
    }
    struct Result {
        let publicKeyPath: String
        let programPath: String
        let binDirectory: String
    }

    /// Write `~/.minisign/passeport.pub` and a `minisign` wrapper, then symlink
    /// the command into `~/.local/bin`. `publicKeyFile` is the public-key contents;
    /// `helperPath` is the bundled `passeport-core`; `socketPath` is the bridge
    /// socket the wrapper signs through.
    static func configure(
        publicKeyFile: String,
        helperPath: String,
        socketPath: String,
        installStandardAlias: Bool = false
    ) throws -> Result {
        let dir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Passeport", isDirectory: true)
            .appendingPathComponent("minisign", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        // Migrate away from the earlier Application Support location so there
        // is only one documented public-key file after reconfiguration.
        let legacyPublicKey = dir.appendingPathComponent("passeport.pub")
        if FileManager.default.fileExists(atPath: legacyPublicKey.path) {
            try FileManager.default.removeItem(at: legacyPublicKey)
        }

        let keyDirectory = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".minisign", isDirectory: true)
        try FileManager.default.createDirectory(
            at: keyDirectory,
            withIntermediateDirectories: true,
            attributes: [.posixPermissions: 0o700]
        )
        try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: keyDirectory.path)

        let publicKey = keyDirectory.appendingPathComponent("passeport.pub")
        var contents = publicKeyFile
        if !contents.hasSuffix("\n") { contents += "\n" }
        try contents.write(to: publicKey, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o644], ofItemAtPath: publicKey.path)

        // A single `minisign`: `-S` signs through the app, `-V` verifies, `-R`
        // prints your public key. The wrapper injects the bridge socket (for
        // signing) and the public-key path (for -R / default verify).
        let legacyProgram = dir.appendingPathComponent("minisign")
        let program = dir.appendingPathComponent("passeport-minisign")
        let script = """
        #!/bin/bash
        # Generated by Passeport. `passeport-minisign -Sm <file>` signs through
        # the app's approval policy; `passeport-minisign -Vm <file> -p <key>` verifies.
        export PASSEPORT_SCD_SOCKET=\(ShellQuote.quote(socketPath))
        export PASSEPORT_MINISIGN_PUBKEY=\(ShellQuote.quote(publicKey.path))
        exec \(ShellQuote.quote(helperPath)) minisign "$@"
        """
        try script.write(to: program, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: program.path)

        let binDir = try installLink(program: program)
        try updateStandardAlias(
            named: "minisign",
            target: program,
            legacyTarget: legacyProgram,
            enabled: installStandardAlias
        )

        return Result(
            publicKeyPath: publicKey.path,
            programPath: program.path,
            binDirectory: binDir.path
        )
    }

    private static func installLink(program: URL) throws -> URL {
        let localBin = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".local/bin", isDirectory: true)
        try FileManager.default.createDirectory(at: localBin, withIntermediateDirectories: true)
        let link = localBin.appendingPathComponent(program.lastPathComponent)
        if FileManager.default.fileExists(atPath: link.path) {
            try FileManager.default.removeItem(at: link)
        }
        try FileManager.default.createSymbolicLink(at: link, withDestinationURL: program)
        return localBin
    }

    private static func updateStandardAlias(
        named name: String,
        target: URL,
        legacyTarget: URL,
        enabled: Bool
    ) throws {
        let alias = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".local/bin", isDirectory: true)
            .appendingPathComponent(name)
        let ownedTargets = [target.path, legacyTarget.path]
        let existingTarget = try? FileManager.default.destinationOfSymbolicLink(atPath: alias.path)
        let isOwned = existingTarget.map { ownedTargets.contains(URL(fileURLWithPath: $0, relativeTo: alias.deletingLastPathComponent()).standardized.path) } ?? false

        guard enabled else {
            if isOwned { try FileManager.default.removeItem(at: alias) }
            return
        }
        if FileManager.default.fileExists(atPath: alias.path) || existingTarget != nil {
            guard isOwned else {
                throw CocoaError(.fileWriteFileExists, userInfo: [
                    NSFilePathErrorKey: alias.path,
                    NSLocalizedDescriptionKey: "Cannot install the `minisign` alias because \(alias.path) is not managed by Passeport."
                ])
            }
            try FileManager.default.removeItem(at: alias)
        }
        try FileManager.default.createSymbolicLink(at: alias, withDestinationURL: target)
    }
}
